@startuml

skinparam backgroundColor cdcdcd
skinparam Shadowing true

left to right direction

rectangle "8010, Mercenário 2, 2012" as filmeMercenario #orange/white;line.bold

together{
  rectangle "1002, Leonardo DiCaprio, **Jack Dawson**" as artistaLeonardo #green/white;line.bold
  rectangle "<color:White>1003, Kate Winslet, <b>Rose</b></color>" as artistaKate2 #green;line.bold;
  rectangle "<color:White>1005, Kate Winslet, <b>Jeanine</b></color>" as artistaKate1 #green;line.bold;
  
  rectangle "8012, Divergent, 2014" as filmeDivergent #orange/white;line.bold
  rectangle "8011, Titanic, 1997" as filmeTitanic #orange/white;line.bold
}  

rectangle "1001, Jean-Claude Van Damme, **Vilain**" as artistaJean #green/white;line.bold
rectangle "1004, Sylvester Stallone, **Barney Ross**" as artistaSylvester #green/white;line.bold


''=========================  RELACOES  ==================================

filmeMercenario -[#black,bold]- artistaJean
filmeMercenario -[#black,bold]- artistaSylvester

filmeTitanic -[#black,bold]- artistaKate1 : \t\t
filmeTitanic -[#black,bold]- artistaLeonardo
filmeDivergent -[#black,bold]- artistaKate2 : \t\t

@enduml
