@startuml

'if encadeado

!$a = 42
!$b = 8
!$result?= ""

!if (0)
  !if ($a > $b)
    !$result = $a
  !else
    !$result = $b
  !endif  
!elseif ($b > $a)
    !$result = $b
!else
    !$result = "nenhum"
!endif



rectangle "Resultado:$result" as result #cdcdcd

note top : Somar


@enduml