@startuml

!$iconPaths = [
    "<tupadr3/devicons/python>", "<tupadr3/devicons/php>", "<tupadr3/devicons/mysql>",
    "<logos/java>", "<logos/arduino>", "<logos/bun>"
  ]

!$logoPy = $python
!$logoPhp = $php
!$logoMySql = $mysql
!$logoJava = $java
!$logoArduino = $arduino

!$logos = ["$python", "$php", "$mysql", "$java", "$arduino","$bun"]
!$textos = ["Python", "PHP", "MySql", "Java \\n Incrível", "\\nArduino", "Bun"]
!$apelidos = ["py", "php", "MySql", "java", "arduino", "bun"]
!$estilos = ["estilo1", "estilo2", "estilo1", "estilo2", "estilo1", "estilo2"]
!$cores = ["white", "black", "blue", "orange", "gold"]


!procedure $createRectangle($i, $logos, $textos, $apelidos, $estilos)
  !while ($i < %size($apelidos))
    !include $iconPaths[$i]
    rectangle "<$logos[$i]>\n $textos[$i]" as $apelidos[$i] <<$estilos[$i]>> 
    !$i = $i + 1
  !endwhile  
!endprocedure 
      
!$cont = 0      
$createRectangle($cont, $logos, $textos, $apelidos, $estilos)


skinparam rectangle {
  backgroundColor<<estilo1>> LightSalmon
  borderColor<<estilo1>> Red
  FontColor<<estilo1>> black
  
  borderColor<<estilo2>> Red
  backgroundColor<<estilo2>> teal
  FontColor<<estilo2>> white
}


hide stereotype



@enduml
