@startuml

'============ CURSO
!$clsCurso = "Curso"
!$aliasCurso = "curso"
!$idCurso = "1"
!$listQualifsAtribsCurso = ["+", "+", "+"]
!$listAtribsCurso = ["nome", "codigo", "duracao"]
!$listDadosCurso = ["String", "integer", "integer"]
!$listQualifsMetodosCurso = ["+"," +"]
!$metodosCurso = ["listarEstudantes(): List<Estudante>", "adicionarEstudante(e: Estudante): bool"]

!$validacaoMetodosCurso = 1
'============ TURMA
!$clsTurma = "Turma"
!$aliasTurma = "turma"
!$idTurma = "2"
!$listQualifsAtribsTurma = ["+", "+", "+", "+", "+"]
!$listAtribsTurma = ["codigo", "ano", "semestre", "disciplina", "professor"]
!$listDadosTurma = ["String", "integer", "integer", "Disciplina", "Professor"]
!$listQualifsMetodosTurma = ["+", "+"]
!$metodosTurma = ["adicionarEstudante(e: Estudante): void", "listarEstudantes(): List<Estudante>"]

!$validacaoMetodosTurma = [1]


!$listValidacaoQualificadores = [1, 1, 1, 1, 1, 1]


' ----------  createClass  ---------------


!procedure $createClass($itemClass, $alias, $id, $arraytQualifsAtribs, $arrayAtribs, $arraytQualifsMetodos, $arrayDados, $validaMetodo, $arrayMetodos) 
  !$j = 0
  
  'Inclui qualificadores'
  !if (1)    
    class "$itemClass" as $alias 
      $alias : <<oid>> id : $id
      !while ($j < %size($arrayAtribs))
        $alias : $arraytQualifsAtribs[$j] $arrayAtribs[$j] : $arrayDados[$j]
        !$j = $j + 1
      !endwhile
      
      !if ($validaMetodo)
        !$k = 0
        !while ($k < %size($arrayMetodos))
          $alias : $arraytQualifsMetodos[$k] $arrayMetodos[$k]  
        !$k = $k + 1
        !endwhile
      !endif
  'Sem qualificadores'    
  !else 
    class "$itemClass" as $alias 
      $alias : <<oid>> id : $id
      !while ($j < %size($arrayAtribs))
        $alias : $arrayAtribs[$j] : $arrayDados[$j]
        !$j = $j + 1
      !endwhile
      
      !if ($validaMetodo)
        !$k = 0
        !while ($k < %size($arrayMetodos))
          $alias : $arrayMetodos[$k]  
        !$k = $k + 1
        !endwhile
      !endif
  !endif  
      
  
!endprocedure



$createClass($clsCurso, $aliasCurso, $idCurso, $listQualifsAtribsCurso, $listAtribsCurso, $listQualifsMetodosCurso, $listDadosCurso, $validacaoMetodosCurso, $metodosCurso)
$createClass($clsTurma, $aliasTurma, $idTurma, $listQualifsAtribsTurma, $listAtribsTurma, $listQualifsMetodosTurma, $listDadosTurma, $validacaoMetodosTurma, $metodosTurma)


turma -- curso



@enduml
